### ISSUE TITLE
Training killed during evaluation

### ISSUE THREAD

**Issue by kulkarnikeerti** [yjh0410/PyTorch_YOLO-Family#9]
Hi @yjh0410 

When a model is training, during the evaluation phase training is killed. This has happened many a times. How do I overcome this?

Also, the evaluation phase does not use the GPU. could you please help me understand this? How this would work?

Thanks in advance.

**Comment by kulkarnikeerti** [comment]
I still have this issue. Model evaluation does not use the GPU at all, and it gets killed everytime. Do I have to set anything to make use of the GPU during evaluation @yjh0410 ?

I tried to reduce the number of workers but that didn't help me. Do you have any suggestions which I could give a try?

**Comment by kulkarnikeerti** [comment]
I tried to reduce the number of workers but that didn't help me. Do you have any suggestions which I could give a try?

**Comment by yjh0410** [comment]
@kulkarnikeerti 
In my project, after `eval_epoch`, the model is evaluated on the val dataset. During evaluation stage, the training phase is paused. During evaluation stage, model make inference on the GPU (At beginning of the whole training pipeline, you must use `--cuda` to deploy the model on GPU) while the calculation of mAP is computed on the CPU since it is unnecessary to use GPU to calculate mAP. After evaluation, the training phase goes on.

**Comment by yjh0410** [comment]
@kulkarnikeerti 
In my project, after `eval_epoch`, the model is evaluated on the val dataset. During evaluation stage, the training phase is paused. During evaluation stage, model make inference on the GPU (At beginning of the whole training pipeline, you must use `--cuda` to deploy the model on GPU) while the calculation of mAP is computed on the CPU since it is unnecessary to use GPU to calculate mAP. After evaluation, the training phase goes on.

**Comment by kulkarnikeerti** [comment]
@yjh0410 thanks. I understand that. I have set the `eval_epoch` to `10` and using `--cuda` from beginning. But for some reason the evaluation stage does not run on GPU which I don't understand. It takes more than an hour to get the evaluation done. Is this time normal? as per my understanding if it runs on GPU, it should not take so long for 5k images.

**Comment by yjh0410** [comment]
@kulkarnikeerti 
More than 1 hour... it might be unusual. May I know the type of your GPU?

**Comment by kulkarnikeerti** [comment]
@yjh0410 
It's `Nvidia GeForce RTX 3090`. Would it make any difference?

**Comment by yjh0410** [comment]
@kulkarnikeerti 
I have tried on my 3090 GPU, but I didn't meet the trouble the same as yours. As for now, I really have no idea how to solve your this issue, I will try again on my device. If I find a solution, I will share with you.

**Comment by kulkarnikeerti** [comment]
@yjh0410 Thanks. Training runs on GPU without any issues and it is fast. But the evaluation takes very long, I thought I would have to set something to use GPU. But anyway, I will try to find from my end too. Please let me know once you try on your device. Thanks again.
